#macro MESSAGE_JOIN 1
#macro MESSAGE_HAND_CHANGE 2
#macro MESSAGE_FIELD 3
#macro MESSAGE_INFIRMARY 4
#macro MESSAGE_MOMENTUM_DECK 5
#macro MESSAGE_STATS 6
#macro MESSAGE_FIELD_CARD_STATS 7
#macro MESSAGE_DECK_CHANGE 8
#macro MESSAGE_OPPONENT_STATS 9
#macro MESSAGE_OPPONENT_FIELD_CARD_STATS 10
#macro MESSAGE_OPPONENT_DECK_CHANGE 11
#macro MESSAGE_OPPONENT_INFIRMARY 12
#macro MESSAGE_OPPONENT_MOMENTUM_DECK 13
#macro MESSAGE_OPPONENT_FIELD 14
#macro MESSAGE_OPPONENT_HAND_CHANGE 15
#macro MESSAGE_TURN 16
#macro MESSAGE_LAST_ACTION 17
#macro MESSAGE_END_TURN 18
#macro MESSAGE_WIN 19
#macro MESSAGE_LEAVE 20
#macro MESSAGE_ASK_RESPONSE 21
#macro MESSAGE_HANDLE_RESPONSE 22
#macro MESSAGE_HANDLE_FAIL 23
#macro MESSAGE_OUTDATED 99

#macro RESPONSE_TARGET_FIELD 0
#macro RESPONSE_TARGET_HAND 1
#macro RESPONSE_TARGET_INFIRMARY 2
#macro RESPONSE_TARGET_MOMENTUM_DECK 3
#macro RESPONSE_TARGET_DECK 4
#macro RESPONSE_TARGET_INFIRMARY_NAME 5
#macro RESPONSE_CHOOSE_FIELD_ZONE 6
#macro RESPONSE_CHOICE 7

if(macros.test_mode){
	connect = scr_client_connect("127.0.0.1", 9001); //self
}else{
	connect = scr_client_connect("127.0.0.1", 9001); //self
}
persistent= true;